### ISSUE TITLE
Unpacking on Web

### ISSUE THREAD

**Issue by samudebug** [birchroad/node-jspack#15]
Hello, I wanted to know if this package works on web. 

I've tried using it on node.js and it worked just fine, but when I got to use it on web, the values that were supposed to be int came as NaN.

**Comment by dgarciabriseno** [comment]
For anyone reading this today, I can attest that this module works in the browser if you're using ES6 modules. I'm using webpack so the following code works for me.

```javascript
import { jspack } from "jspack";

let value = jspack.Unpack("<i", uint8buffer)[0];
```

**Comment by kmpm** [comment]
thanks fof testing
